### ISSUE TITLE
no folder for assignment 2

### ISSUE THREAD

**Issue by lulamae12** [utk-cs340-fall22/students#54]
I was going to do Assignment 2: Project Ideas but i cant find the folder in the repo.

**Comment by davidalanreid** [comment]
The project-ideas repo for assignment 2 is a private repo. Once you have been added as a member of the utk-cs340-fall22 organization on github, you will have access to that repo. You will be added as a member when the TAs grade assignment 1, which includes your github id that is needed to add you.

**Comment by davidalanreid** [comment]
I changed this to a public repo, so now you should be able to see it and clone it, but you still won't be able to push until you are added as a member of the organization.
